### ISSUE TITLE
Building will fail for Python 3.10

### ISSUE THREAD

**Issue by sphuber** [materialsproject/pymatgen#2332]
**Describe the bug**
Building fails for Python 3.10 because the `pymatgen/optimization/neighbors.c` uses an undocumented struct member `use_tracing` that was removed. See this issue for reference: https://bugs.python.org/issue43760
I know that the package does not officially state support for Python 3.10, but wanted to give the heads-up.

**To Reproduce**
Try to build the package with Python 3.10 which should show the following stack trace (only last part pasted for clarity)

```
....
  pymatgen/optimization/neighbors.c:25711:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
  25711 |     tstate->use_tracing = (tstate->c_profilefunc ||
        |             ^~~~~~~~~~~
        |             tracing
  pymatgen/optimization/neighbors.c:25716:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
  25716 |         return tstate->use_tracing && retval;
        |                        ^~~~~~~~~~~
        |                        tracing
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pymatgen
```

**Desktop (please complete the following information):**
 - Verified on Ubuntu 20.04

**Comment by shyuep** [comment]
@chc273 Can you look into this?

**Comment by chc273** [comment]
@shyuep on it.

**Comment by chc273** [comment]
@shyuep This is mostly a Cython version issue. The older Cython generated the C code that does not work with python 3.10.  It should have been fixed by your commits yesterday 40c1ff014908a08f11af05f58b252f8764df5bf7 

I have tested on Ubuntu 20.04.3 LTS with a new python 3.10 conda env. I was able to build the cython code without problem.

**Comment by chc273** [comment]
Additionally, it seems that pip of python 3.10 does not find scipy 1.7.1 on my mac and ubuntu, changing https://github.com/materialsproject/pymatgen/blob/0ac6a086d248467a95f635d97ba6db377c9d0b7a/requirements.txt#L6 to 1.7.3 makes it work.

**Comment by shyuep** [comment]
@sphuber I have confirmed that everything works fine but Boltztrap is still not compatible with 3.10. That's an optional dependency.
