### PR TITLE
Officially support Python 3.12 and test in CI

### PR DESCRIPTION
**Pull request by janosh**
unknown if all upstream packages have 3.12 support by now. potential issues expected for `pytorch` and `spglib` https://github.com/materialsproject/atomate2/pull/768#issuecomment-1988198169.

### CODE REVIEW

**Comment by janosh** [comment]
`chgnet` cythonized graph converter doesn't compile on 3.12:

```py
chgnet/graph/cygraph.c:1208:10: fatal error: fast_converter_libraries/create_graph.c: No such file or directory
 1208 | #include "fast_converter_libraries/create_graph.c"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by janosh** [comment]
@JaGeo some of the lobster tests started failing under Python 3.12. i fixed all but two. maybe you know what needs to change here?

```py
____________________ TestLobsterin.test_dict_functionality _____________________

self = <lobster.test_inputs.TestLobsterin testMethod=test_dict_functionality>

    def test_dict_functionality(self):
        for key in ("COHPstartEnergy", "COHPstartEnergy", "COhPstartenergy"):
            start_energy = self.Lobsterin.get(key)
>           assert start_energy == -15.0, f"{start_energy=}"
E           AssertionError: start_energy=None

tests/io/lobster/test_inputs.py:1773: AssertionError
___________________ TestLobsterin.test_read_write_lobsterin ____________________

self = <lobster.test_inputs.TestLobsterin testMethod=test_read_write_lobsterin>

    def test_read_write_lobsterin(self):
        outfile_path = tempfile.mkstemp()[1]
        lobsterin1 = Lobsterin.from_file(f"{TEST_DIR}/lobsterin.1")
        lobsterin1.write_lobsterin(outfile_path)
        lobsterin2 = Lobsterin.from_file(outfile_path)
>       assert lobsterin1.diff(lobsterin2)["Different"] == {}
E       AssertionError

tests/io/lobster/test_inputs.py:1793: AssertionError
```

**Comment by JaGeo** [comment]
@janosh : see https://github.com/materialsproject/pymatgen/issues/3775

**Comment by JaGeo** [comment]
@janosh could you try this solution for now? 
https://github.com/python/cpython/issues/105524#issuecomment-1610750842

**Comment by janosh** [comment]
@JaGeo oh right, i forgot about our `UserDict` discussion in #3757.

if possible, i'd prefer to drop `UserDict` altogether and make `Lobsterin` inherit directly from `dict`. do you remember [what exactly the issues it solves are](https://github.com/materialsproject/pymatgen/pull/3757#issuecomment-2057411158)?

**Comment by JaGeo** [comment]
We had issues in #3439 that the Userdict solved.

**Comment by janosh** [comment]
@JaGeo the suggested fix [you linked](https://github.com/materialsproject/pymatgen/pull/3685#issuecomment-2081967584) doesn't work (see [da1f7c5](https://github.com/materialsproject/pymatgen/pull/3685/commits/da1f7c59a96203073918df245b62a222482c06a1)). i'm still unclear what benefits `UserDict` offers after having looked at https://github.com/materialsproject/pymatgen/pull/3439

**Comment by JaGeo** [comment]
I can try again in the next days. Need to fix other stuff as well. Sorry that this functionality here is such a pain.

**Comment by janosh** [comment]
the thing making this hard to debug is that i can't repro the issue locally. even on 3.12, everything works for me. don't understand why this would be linux-specific (if it is)

**Comment by JaGeo** [comment]
> the thing making this hard to debug is that i can't repro the issue locally. even on 3.12, everything works for me on macOS. don't understand why this would be linux-specific (if it is)

Fixes everything except for a temp_path problem. Not sure where this is coming from. will check and see if I can fix it as well.

**Comment by JaGeo** [comment]
@janosh tests should be passing locally now for py 3.12. You might want to check the tmp_dir change. The rest should hopefully be fine now.

**Comment by JaGeo** [comment]
3.9 and 3.12 tests are passing. 3.11 does not run.

**Comment by janosh** [comment]
> 3.9 and 3.12 tests are passing

perfect! thanks! 👍 

> 3.11 does not run.

that's intentional. no point in wasting Ci budget. usually enough to test the oldest and newest boundaries of supported versions. i'll update the required status checks before merging here to make 3.12 tests instead of 3.11 required

> You might want to check the tmp_dir change

done. i refactored the test slightly and deleted the new test files. i assume they were added by accident?
